### ISSUE TITLE
Password: chpasswd: PAM: Authentication token manipulation error

### ISSUE THREAD

**Issue by Razorsheep** [onjin/docker-alpine-vsftpd#3]
Interesting repo, but how did you solve this current bug when trying to use chpasswd in alpine?

Password: chpasswd: PAM: Authentication token manipulation error

**Comment by onjin** [comment]
I tried to reproduce this error with steps

`
$ docker run -it --rm  -v ${PWD}/files:/home/files -e PASSWORD=files --name vsftpd onjin/alpine-vsftpd
$ docker exec -it vsftpd sh
/ # chpasswd
files:newpass
chpasswd: password for 'files' changed
`
so password has been changed properly.

If you can provide the steps required to reproduce chpass problem, i will check it.

**Comment by Razorsheep** [comment]
Thanks for your attention, this issue was with the version of Alpine I was using in my own project. I'll close this issue.
